# -*- coding: utf-8 -*-
"""model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TELiLVSPoZm0vT6386JKlFJAwyc_z2P
"""

import os
import gdown
import numpy as np
import cv2
from tensorflow.keras.models import load_model

MODEL_URL = "https://drive.google.com/uc?export=download&id=11yMXnD0PjejksRK3kg-p3UU6bFUs96Dx"
MODEL_PATH = "fracture_model.keras"

def download_model():
    if not os.path.exists(MODEL_PATH):
        print("Downloading trained model...")
        gdown.download(MODEL_URL, MODEL_PATH, quiet=False)
        print("Download complete.")

def load_trained_model():
    download_model()
    model = load_model(MODEL_PATH)
    return model

def preprocess_image(image_path):
    img = cv2.imread(image_path)
    img = cv2.resize(img, (224, 224))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)
    return img

def predict(image_path):
    model = load_trained_model()
    processed_img = preprocess_image(image_path)
    prediction = model.predict(processed_img)

    if prediction[0][0] > 0.5:
        return "Fracture Detected"
    else:
        return "Normal"

if __name__ == "_main_":
    test_image = "test.jpg"
    result = predict(test_image)
    print("Prediction:", result)